version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2
    container_name: es01
    network_mode: "host"
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
